name: Pull Request to Develop

on:
  pull_request:
    branches: [ "develop" ]

jobs:

  branch-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ ${{ github.head_ref }} = feature*  ] || [ ${{ github.head_ref }} = hotfix* ]
          then
            echo "${{ github.head_ref }} branch is allowed"
          else
            exit 1
          fi
        shell: bash

  docker-image-build:
    needs: branch-check
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Latest Commit Id"
        run: echo ${{ github.event.pull_request.head.sha }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: canpolatoral/${{ github.event.repository.name }}:${{ github.run_number }}, canpolatoral/${{ github.event.repository.name }}:${{ github.event.pull_request.head.sha }}, canpolatoral/${{ github.event.repository.name }}:latest