name: Pull Request CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: canpolatoral/hello-world:0.${{github.run_number}}


  change-deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          name: canpolatoral/hello-world-config
          ref: refs/heads/main

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm-charts/hello-world/values.yaml'
          propertyPath: 'image.tag'
          value: 0.${{github.run_number}}
          message: CD Change by Pipeline
          commitChange: true
          updateFile: true
      
      
      
      
