name: Push to Main

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]
  # push:
  #   branches: [ "main" ]

env:
  PR_LATEST_COMMIT: ${{ github.event.pull_request.head.sha }}

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ${{ github.event.pull_request.merged }} = true ]]
          then
            echo "Merge completed"
          else
            exit 1
          fi
        shell: bash

  prod-deployment:
    needs: pr-check
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}-config
          ref: refs/heads/main
          path: './${{ github.event.repository.name }}-config'

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Latest Commit Id"
        run: echo ${{ env.PR_LATEST_COMMIT }}

      - name: Update values-prod.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.repository }}-config
          workDir: '${{ github.event.repository.name }}-config'
          valueFile: 'helm-charts/${{ github.event.repository.name }}/values-prod.yaml'
          propertyPath: 'image.tag'
          value: ${{ env.PR_LATEST_COMMIT }}
          branch: main
          masterBranchName: main
          targetBranch: main
          token: ${{ secrets.CONFIG_PAT }}
          message: CD Change by Pipeline
          commitChange: true
          updateFile: true
      
      
      
      
