name: Push to Main

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

jobs:
  call-workflow:
    uses: canpolato/core-pipelines/.github/workflows/core-push-main.yml
      
      
      
      
