name: Push to Develop

on:
  push:
    branches: [ "develop" ]

jobs:

  dev-deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ github.event.org.id }}/${{ github.event.repository.name }}-config
          ref: refs/heads/main
          path: './${{ github.event.repository.name }}-config'

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Latest Commit Id"
        run: echo ${{ github.event.commits[0].id }}

      - name: Update values-dev.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.event.org.id }}/${{ github.event.repository.name }}-config
          workDir: '${{ github.event.repository.name }}-config'
          valueFile: 'helm-charts/${{ github.event.repository.name }}/values-dev.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.event.commits[0].id }}
          branch: main
          masterBranchName: main
          targetBranch: main
          token: ${{ secrets.CONFIG_PAT }}
          message: CD Change by Pipeline
          commitChange: true
          updateFile: true
      
  tag-image:
    name: Tag image
    runs-on: ubuntu-latest
    needs: dev-deployment
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker pull canpolatoral/${{ github.event.repository.name }}:${{ github.event.commits[0].id }}
          docker tag canpolatoral/${{ github.event.repository.name }}:${{ github.event.commits[0].id }} canpolatoral/${{ github.event.repository.name }}:dev
          docker push canpolatoral/${{ github.event.repository.name }}