name: Push to Develop

on:
  pull_request:
    types: [ closed ]
    branches: [ "develop" ]
  # push:
  #   branches: [ "develop" ]

env:
  PR_LATEST_COMMIT: ${{ github.event.pull_request.head.sha }}

jobs:

  dev-deployment:
    if: |
      (startsWith(github.head_ref, 'feature') || startsWith(github.head_ref, 'hotfix')
      && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}-config
          ref: refs/heads/main
          path: './${{ github.event.repository.name }}-config'

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Latest Commit Id"
        run: echo ${{ env.PR_LATEST_COMMIT }}

      - name: Update values-dev.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.repository }}-config
          workDir: '${{ github.event.repository.name }}-config'
          valueFile: 'helm-charts/${{ github.event.repository.name }}/values-dev.yaml'
          propertyPath: 'image.tag'
          value: ${{ env.PR_LATEST_COMMIT }}
          branch: main
          masterBranchName: main
          targetBranch: main
          token: ${{ secrets.CONFIG_PAT }}
          message: CD Change by Pipeline
          commitChange: true
          updateFile: true
      
  tag-image:
    name: Retag Image as DEV
    runs-on: ubuntu-latest
    needs: dev-deployment
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker pull canpolatoral/${{ github.event.repository.name }}:${{ env.PR_LATEST_COMMIT }}
          docker tag canpolatoral/${{ github.event.repository.name }}:${{ env.PR_LATEST_COMMIT }} canpolatoral/${{ github.event.repository.name }}:dev
          docker push canpolatoral/${{ github.event.repository.name }}:dev