name: Push to Release

on:
  push:
    branches: [ "release/*" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Latest Commit Id"
        run: echo ${{ github.sha }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: canpolatoral/${{ github.event.repository.name }}:sit, canpolatoral/${{ github.event.repository.name }}:${{ github.run_number }}, canpolatoral/${{ github.event.repository.name }}:${{ github.sha }}, canpolatoral/${{ github.event.repository.name }}:latest

  sit-deployment:
    runs-on: ubuntu-latest
    needs: docker
    environment: sit
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}-config
          ref: refs/heads/main
          path: './${{ github.event.repository.name }}-config'

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Latest Commit Id"
        run: echo ${{ github.sha }}

      - name: Update values-sit.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.repository }}-config
          workDir: '${{ github.event.repository.name }}-config'
          valueFile: 'helm-charts/${{ github.event.repository.name }}/values-sit.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.sha }}
          branch: main
          masterBranchName: main
          targetBranch: main
          token: ${{ secrets.CONFIG_PAT }}
          message: CD Change by Pipeline
          commitChange: true
          updateFile: true

  uat-deployment:
    runs-on: ubuntu-latest
    needs: sit-deployment
    environment: uat
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}-config
          ref: refs/heads/main
          path: './${{ github.event.repository.name }}-config'

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Latest Commit Id"
        run: echo ${{ github.sha }}

      - name: Update values-sit.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.repository }}-config
          workDir: '${{ github.event.repository.name }}-config'
          valueFile: 'helm-charts/${{ github.event.repository.name }}/values-uat.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.sha }}
          branch: main
          masterBranchName: main
          targetBranch: main
          token: ${{ secrets.CONFIG_PAT }}
          message: CD Change by Pipeline
          commitChange: true
          updateFile: true
      
      
  pt-deployment:
    runs-on: ubuntu-latest
    needs: uat-deployment
    environment: pt
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}-config
          ref: refs/heads/main
          path: './${{ github.event.repository.name }}-config'

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "Latest Commit Id"
        run: echo ${{ github.sha }}

      - name: Update values-sit.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.repository }}-config
          workDir: '${{ github.event.repository.name }}-config'
          valueFile: 'helm-charts/${{ github.event.repository.name }}/values-pt.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.sha }}
          branch: main
          masterBranchName: main
          targetBranch: main
          token: ${{ secrets.CONFIG_PAT }}
          message: CD Change by Pipeline
          commitChange: true
          updateFile: true
      
